Repository rpm-software-management/mock, pull requests merged in 2024-08, with the labels that each got.

#1416 openEuler 24.03 LTS
  mock-core-configs/etc/mock/openeuler-24.03-aarch64.cfg
  mock-core-configs/etc/mock/openeuler-24.03-x86_64.cfg
  mock-core-configs/etc/mock/templates/openeuler-24.03.tpl
  releng/release-notes-next/add-openeuler-2403.config
Labels: bot:chronographer:provided

#1367 Enable RPM sysusers integration
  mock-core-configs/mock-core-configs.spec
  mock/mock.conf
  mock/mock.spec
  releng/release-notes-next/sysusers-handled-by-rpm.feature
Labels: bot:chronographer:provided

#1422 configs: branch F41
  mock-core-configs/etc/mock/fedora-41-aarch64.cfg
  mock-core-configs/etc/mock/fedora-41-i386.cfg
  mock-core-configs/etc/mock/fedora-41-ppc64le.cfg
  mock-core-configs/etc/mock/fedora-41-s390x.cfg
  mock-core-configs/etc/mock/fedora-41-x86_64.cfg
  mock-core-configs/etc/mock/fedora-42-aarch64.cfg
  mock-core-configs/etc/mock/fedora-42-i386.cfg
  mock-core-configs/etc/mock/fedora-42-ppc64le.cfg
  mock-core-configs/etc/mock/fedora-42-s390x.cfg
  mock-core-configs/etc/mock/fedora-42-x86_64.cfg
  mock-core-configs/etc/mock/templates/fedora-eln.tpl
  mock-core-configs/etc/mock/templates/fedora-rawhide.tpl
  mock-core-configs/mock-core-configs.spec
  releng/release-notes-next/fedora-41-branching.feature
Labels: bot:chronographer:provided

#1423 Enable mock stable repostory in TF
  mock/integration-tests/setup-playbook/tasks/main.yml
Labels: release-blocker, no-release-notes, bot:chronographer:provided

#1424 Add CentOS Stream 10 + EPEL 10 configs
  mock-core-configs/etc/mock/centos-stream+epel-10-aarch64.cfg
  mock-core-configs/etc/mock/centos-stream+epel-10-ppc64le.cfg
  mock-core-configs/etc/mock/centos-stream+epel-10-s390x.cfg
  mock-core-configs/etc/mock/centos-stream+epel-10-x86_64.cfg
  mock-core-configs/etc/mock/templates/epel-10.tpl
  releng/release-notes-next/c10s+epel.config
Labels: bot:chronographer:provided

#1425 Release mock-core-configs v41.1
  .tito/packages/mock-core-configs
  docs/Release-Notes-Configs-41.1.md
  docs/index.md
  mock-core-configs/mock-core-configs.spec
  releng/release-notes-next/add-openeuler-2403.config
  releng/release-notes-next/c10s+epel.config
  releng/release-notes-next/c10s-metalink.config
  releng/release-notes-next/centos-7-eol.config
  releng/release-notes-next/fedora-41-branching.feature
  releng/release-notes-next/fedora-eln-i386.config
  releng/release-notes-next/fedora-rawhide-key-plus-one.config
  releng/release-notes-next/rawhide-bootstrap-image-ready.config
Labels: no-release-notes

#1431 The installed_pkgs.log file now covers dynamic builddeps
  docs/Plugin-Hooks.md
  mock/py/mockbuild/backend.py
  mock/py/mockbuild/plugins/package_state.py
  releng/release-notes-next/package-state-after-deps-resolved.bugfix
Labels: bot:chronographer:provided

#1430 Skip the "podman pull" for bootstrap when not needed
  mock/docs/site-defaults.cfg
  mock/py/mockbuild/buildroot.py
  mock/py/mockbuild/config.py
  releng/release-notes-next/bootstrap-skip-image-pull.feature
Labels: bot:chronographer:provided

#1435 towncrier: update to v45 && use defaults
  .github/workflows/towncrier.yml
Labels: no-release-notes

#1438 ci: chronographer to accept "no-release-notes"
  .github/chronographer.yml
Labels: no-release-notes
