Repository rpm-software-management/mock, pull requests merged in 2024-09, with the labels that each got.

#1440 Configure Chronographer to skip labeling label-detected PRs
  .github/chronographer.yml
Labels: no-release-notes

#1441 Add runtime dependency on fuse-overlayfs
  mock/mock.spec
  releng/release-notes-next/fuse-overlayfs.bugfix
Labels: no-release-notes

#1439 ci: update vcs-diff-lint config
  .github/workflows/python-diff-lint.yml
Labels: no-release-notes

#1437 doc: slight update of the package_state plugin docs
  docs/Plugin-PackageState.md
Labels: no-release-notes

#1444 CI: lint the whole project
  .github/workflows/python-diff-lint.yml
  pylintrc
Labels: no-release-notes

#1447 ci: allow us to skip Packit builds with "no-ci-builds" label
  .github/workflows/copr-builds.yml
  .github/workflows/fedora-tox.yml
  .packit.yaml
Labels: no-release-notes, no-ci-builds

#1445 tests: helper for creating new EC2 instances
  mock/integration-tests/setup-box
  mock/integration-tests/setup-playbook/group_vars/.gitignore
  mock/integration-tests/setup-playbook/spawn-test-machine-ec2.yaml
Labels: no-release-notes

#1448 ci: fix the no-ci-builds label
  .github/workflows/copr-builds.yml
  .github/workflows/fedora-tox.yml
Labels: no-release-notes, no-ci-builds

#1446 ci: drop our custom Towncrier task
  .github/chronographer.yml
  .github/workflows/towncrier.yml
Labels: no-release-notes

#1461 packit: specify mock-deps as additional_repo
  .packit.yaml
Labels: no-release-notes

#1460 README: copr build status in table
  mock/README.md
Labels: no-release-notes, no-ci-builds

#1466 No per-command bootstrap mount leftovers
  mock/py/mockbuild/util.py
  releng/release-notes-next/buildroot-mounts-redundancy.bugfix
Labels: release-blocker

#1465 add template for pull requests
  .github/pull_request_template.md
Labels: no-release-notes

#1469 Release v5.7
  .tito/packages/mock
  .tito/packages/mock-core-configs
  docs/Release-Notes-5.7.md
  docs/index.md
  mock-core-configs/mock-core-configs.spec
  mock/mock.spec
  releng/release-notes-next/addrepo-affects-bootstrap.feature
  releng/release-notes-next/anolis-7.config
  releng/release-notes-next/bootstrap-skip-image-pull.feature
  releng/release-notes-next/buildroot-mounts-redundancy.bugfix
  releng/release-notes-next/c10s-bootstrap-ready.config.md
  releng/release-notes-next/c9s-image-ready.config
  releng/release-notes-next/ccache-show-stats.feature
  releng/release-notes-next/ccache_debug.feature
  releng/release-notes-next/centos-stream-10-gpg-keys.bugfix
  releng/release-notes-next/dnf4-config-is-alias-to-dnf.feature
  releng/release-notes-next/docdir-ownership.bugfix
  releng/release-notes-next/fuse-overlayfs.bugfix
  releng/release-notes-next/hashdir.feature
  releng/release-notes-next/hermetic-build.feature
  releng/release-notes-next/leap-15-4.config
  releng/release-notes-next/nspawn-args-chroot-bootstrap.bugfix
  releng/release-notes-next/package-state-after-deps-resolved.bugfix
  releng/release-notes-next/ppc64le-not-powerpc64le-host-cpu.config
  releng/release-notes-next/scrub-all-chroots.feature
  releng/release-notes-next/sysusers-handled-by-rpm.feature
  releng/release-notes-next/unified-resultdir-preparation.bugfix
Labels: no-release-notes, no-ci-builds
